
services:
    database:
      container_name: "rb_db"
      image: postgres
      volumes:
        - pg_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: "rp_app_db"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      ports:
        - "5432:5432"

volumes:
  pg_data: